[tool.black]
target_version = ['py310']
line-length = 88
skip-string-normalization = false
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
  | fsspec/_version.py
  | versioneer.py
)
'''

[tool.ruff]
exclude = [
    ".tox",
    "build",
    "docs/source/conf.py",
    "versioneer.py",
    "fsspec/_version",
]
line-length = 88
ignore = [
    # Assigning lambda expression
    "E731",
    # Ambiguous variable names
    "E741",
    # line break before binary operator
    # uncomment when implemented in ruff
    # "W503",
    # whitespace before :
    "E203",
    # redefs
    "F811",
]

[tool.pytest.ini_options]
# custom markers, need to be defined to avoid warnings
markers = [
    "asyncio",
    "vcr",
]
